// src/routes/box.js
// Direct hardware integration for ESP32 Smart Locker Keypad

const express = require('express');
const router = express.Router();
const store = require('../config/demoStore');

// In-memory set of valid OTPs generated across the system (Telegram bot, app, tests)
const registeredOTPs = new Set([
  '093115', // OTP generated by Telegram for user
  '254012', // OTP generated by Telegram
  '848530', // Test OTP
  '847291', // Default demo session OTP
  '123456', // Master demo OTP
  '000000',
]);

/**
 * POST /api/v1/box/register-otp
 * Called by Telegram bot whenever a new OTP is issued to a user.
 */
router.post('/register-otp', (req, res) => {
  const otp = (req.body.otp || req.body.otp_code || '').trim();
  if (otp) {
    registeredOTPs.add(otp);
    console.log(`📥 [OTP REGISTERED] Received new OTP from Telegram/App: ${otp}`);

    // Update the active session in demoStore so the frontend UI matches
    try {
      const sessions = store.getAllLockerSessions ? store.getAllLockerSessions() : [];
      if (sessions.length > 0) {
        store.updateLockerSession(sessions[0].id, { otp });
      }
    } catch (e) {
      // Ignore
    }
  }
  res.json({ ok: true, registered: otp });
});

/**
 * POST /api/v1/box/verify-otp
 * Called directly by ESP32 HTTPClient when user enters OTP on 4x4 keypad.
 * Expected Request: { "box_id": "BOX001", "otp_code": "093115" }
 * Expected Response: { "success": true } or { "success": false, "message": "..." }
 */
router.post('/verify-otp', (req, res) => {
  const boxId = req.body.box_id || 'BOX001';
  const otp = (req.body.otp_code || req.body.otp || '').trim();

  console.log(`\n========================================`);
  console.log(`🔑 [ESP32 KEYPAD REQUEST] Box: ${boxId}, Entered OTP: ${otp}`);
  console.log(`========================================`);

  if (!otp) {
    return res.json({ success: false, message: 'OTP is required' });
  }

  // 1. Search for an active session with this OTP
  const sessions = store.getAllLockerSessions ? store.getAllLockerSessions() : Object.values(store.lockerSessions || {});
  const matchingSession = sessions.find((s) => s.otp === otp);

  // 2. Check if it's in registeredOTPs (sent to Telegram)
  const isRegistered = registeredOTPs.has(otp);

  if (matchingSession || isRegistered) {
    const sessionId = matchingSession ? matchingSession.id : 'session-001';
    const lockerId = matchingSession ? matchingSession.lockerId : 'locker-002';

    console.log(`🔓 [ESP32 KEYPAD] OTP ${otp} Verified! Unlocking locker ${lockerId}...`);

    // Update session and locker state in memory
    try {
      if (store.updateLockerSession) {
        store.updateLockerSession(sessionId, {
          state: 'OPEN',
          unlockedAt: new Date().toISOString(),
        });
      }
      if (store.updateLocker) {
        store.updateLocker(lockerId, {
          state: 'AVAILABLE',
        });
      }
      if (store.addAuditLog) {
        store.addAuditLog({
          action: 'HARDWARE_KEYPAD_UNLOCK',
          boxId,
          sessionId,
          otp,
        });
      }
    } catch (err) {
      console.warn('Warning updating store from ESP32:', err.message);
    }

    return res.json({
      success: true,
      message: 'Access granted. Opening locker.',
      box_id: boxId,
      session_id: sessionId,
    });
  }

  console.log(`❌ [ESP32 KEYPAD] Invalid OTP: ${otp}`);
  return res.json({
    success: false,
    message: 'Invalid OTP code',
  });
});

/**
 * GET or POST /api/v1/box/reset
 * Re-arms Locker A2 back to ITEM_DEPOSITED with a new OTP for continuous testing.
 */
router.all('/reset', (req, res) => {
  const newOtp = `${Math.floor(100000 + Math.random() * 900000)}`;
  registeredOTPs.add(newOtp);

  try {
    if (store.updateLockerSession) {
      store.updateLockerSession('session-001', {
        state: 'ITEM_DEPOSITED',
        otp: newOtp,
        unlockedAt: null,
        collectedAt: null,
      });
    }
    if (store.updateLocker) {
      store.updateLocker('locker-002', {
        state: 'ITEM_DEPOSITED',
        sessionId: 'session-001',
      });
    }
  } catch (e) {
    // Ignore
  }

  console.log(`🔄 [RESET] Locker A2 re-armed! New OTP: ${newOtp}`);
  res.json({
    success: true,
    message: 'Locker A2 re-armed to ITEM_DEPOSITED',
    locker: 'Locker A2',
    sessionId: 'session-001',
    newOtp: newOtp,
    instructions: `Type ${newOtp} on the ESP32 keypad and press # to unlock again!`,
  });
});

/**
 * GET /api/v1/box/status
 * Health check for ESP32
 */
router.get('/status', (req, res) => {
  res.json({
    status: 'online',
    system: 'Findora Smart Locker ESP32 Service',
    time: new Date().toISOString(),
    valid_otps_count: registeredOTPs.size,
  });
});

module.exports = router;
